# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base for the build stage
FROM node:20-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the TypeScript application
RUN npm run build

# Use a minimal Node.js image for the production stage
FROM node:20-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/build ./build

# Copy the package.json for the runtime dependencies
COPY package.json ./

# Install only the production dependencies
RUN npm ci --omit=dev

# Set the entry point for the container
ENTRYPOINT ["node", "build/index.js"]
